name: notes
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  firebase_messaging: ^15.0.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.1.3
  uuid: ^4.4.2
  modal_progress_hud_nsn: ^0.5.1
  fluttertoast: ^8.2.8
  provider: ^6.1.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  auto_size_text: ^3.0.0
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/fonts/inter/
    - assets/vectors/

  fonts:
    - family: 'inter'
      fonts:
        - asset: assets/fonts/inter/inter-Light.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/inter/inter-Regular.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/inter/inter-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/inter/inter-Bold.ttf
          weight: 700
          style: normal
